import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { FileText, Download, Printer, Share2, AlertCircle, CheckCircle2, Clock } from 'lucide-react';

const MedicalReport = ({ report, prediction }) => {
  const [showFullReport, setShowFullReport] = useState(false);

  if (!report) return null;

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="w-full max-w-4xl mx-auto mt-8 bg-white/5 backdrop-blur-xl rounded-2xl border border-white/10 overflow-hidden"
    >
      <div className="p-6 border-b border-white/10 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <FileText className="w-6 h-6 text-blue-400" />
          <h2 className="text-xl font-semibold">AI Medical Report</h2>
        </div>
        <div className="flex gap-2">
          <button className="p-2 hover:bg-white/10 rounded-lg transition-colors" title="Download PDF">
            <Download className="w-5 h-5 text-gray-300" />
          </button>
          <button className="p-2 hover:bg-white/10 rounded-lg transition-colors" title="Print">
            <Printer className="w-5 h-5 text-gray-300" />
          </button>
        </div>
      </div>

      <div className="p-6 space-y-6">
        {/* Header Info */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="bg-white/5 p-4 rounded-xl">
            <p className="text-sm text-gray-400 mb-1">Report ID</p>
            <p className="font-mono">{report.report_id || 'PENDING'}</p>
          </div>
          <div className="bg-white/5 p-4 rounded-xl">
            <p className="text-sm text-gray-400 mb-1">Generated</p>
            <div className="flex items-center gap-2">
              <Clock className="w-4 h-4 text-blue-400" />
              <span>{report.timestamp}</span>
            </div>
          </div>
        </div>

        {/* Clinical Summary */}
        <div className="bg-white/5 p-6 rounded-xl border border-white/5">
          <h3 className="text-lg font-semibold mb-4 text-blue-300">Clinical Analysis</h3>
          <p className="whitespace-pre-wrap leading-relaxed text-gray-200">
            {report.clinical_summary}
          </p>
        </div>

        <div className="flex items-center gap-2 text-sm text-gray-400 bg-blue-500/10 p-4 rounded-lg border border-blue-500/20">
          <AlertCircle className="w-4 h-4 text-blue-400 flex-shrink-0" />
          <p>This report is generated by MedGemma AI model for educational purposes only. Always consult with a qualified medical professional for diagnosis.</p>
        </div>
      </div>
    </motion.div>
  );
};

export default MedicalReport;
